from typing import Dict, List, Optional, Tuple
from datetime import datetime
import io
import base64
from fpdf import FPDF
from app.core.generator_utils import ATSReportPDF, get_score_color_rgb
from app.core.generator_pdf_sections1 import _add_overall_score_section, _add_score_breakdown_section, _add_strengths_section, _add_critical_issues_section, _add_improvements_section
from app.core.generator_pdf_sections2 import _add_skill_validation_section, _add_grammar_section, _add_location_section, _add_jd_comparison_section
from app.core.generator_pdf_sections3 import _add_recommendations_section, _add_action_items_section
from app.core.generator_actions import generate_action_items, generate_action_items_checklist


def generate_pdf_report(analysis_results: Dict, user_info: Optional[Dict]=None
    ) ->bytes:
    pdf = ATSReportPDF()
    pdf.alias_nb_pages()
    pdf.add_page()
    pdf.add_title('ATS Resume Score Report')
    pdf.set_font('Helvetica', 'I', 10)
    pdf.set_text_color(128, 128, 128)
    pdf.cell(0, 6,
        f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
        align='C', new_x='LMARGIN', new_y='NEXT')
    if user_info and user_info.get('name'):
        pdf.cell(0, 6, f"User: {user_info['name']}", align='C', new_x=
            'LMARGIN', new_y='NEXT')
    pdf.ln(10)
    scores = analysis_results.get('scores', {})
    _add_overall_score_section(pdf, scores)
    _add_score_breakdown_section(pdf, scores)
    _add_strengths_section(pdf, analysis_results)
    _add_critical_issues_section(pdf, analysis_results)
    _add_improvements_section(pdf, analysis_results)
    _add_skill_validation_section(pdf, analysis_results)
    _add_grammar_section(pdf, analysis_results)
    _add_location_section(pdf, analysis_results)
    if analysis_results.get('jd_comparison'):
        _add_jd_comparison_section(pdf, analysis_results)
    _add_recommendations_section(pdf, analysis_results)
    _add_action_items_section(pdf, analysis_results)
    return bytes(pdf.output())


def get_pdf_download_link(pdf_bytes: bytes, filename: str='ats_report.pdf'
    ) ->str:
    b64 = base64.b64encode(pdf_bytes).decode()
    return f'data:application/pdf;base64,{b64}'


def generate_summary_text(analysis_results: Dict) ->str:
    scores = analysis_results.get('scores', {})
    overall_score = scores.get('overall_score', 0)
    interpretation = scores.get('overall_interpretation', '')
    clean_interpretation = interpretation
    for emoji in ['🌟', '✅', '👍', '⚠️', '❌', '🔴']:
        clean_interpretation = clean_interpretation.replace(emoji, '')
    clean_interpretation = clean_interpretation.strip()
    lines = ['ATS Resume Analysis Summary', '=' * 30, '',
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", '',
        f'Overall Score: {overall_score:.0f}/100', clean_interpretation, '',
        'Score Breakdown:',
        f"  - Formatting: {scores.get('formatting_score', 0):.0f}/20",
        f"  - Keywords & Skills: {scores.get('keywords_score', 0):.0f}/25",
        f"  - Content Quality: {scores.get('content_score', 0):.0f}/25",
        f"  - Skill Validation: {scores.get('skill_validation_score', 0):.0f}/15"
        ,
        f"  - ATS Compatibility: {scores.get('ats_compatibility_score', 0):.0f}/15"
        , '']
    strengths = analysis_results.get('strengths', [])
    if strengths:
        lines.append('Strengths:')
        for strength in strengths:
            clean_strength = strength
            for emoji in ['✅', '🌟']:
                clean_strength = clean_strength.replace(emoji, '[+]')
            lines.append(f'  {clean_strength}')
        lines.append('')
    critical_issues = analysis_results.get('critical_issues', [])
    if critical_issues:
        lines.append('Critical Issues:')
        for issue in critical_issues:
            clean_issue = issue
            for emoji in ['🔴', '❌']:
                clean_issue = clean_issue.replace(emoji, '[!]')
            lines.append(f'  {clean_issue}')
        lines.append('')
    improvements = analysis_results.get('improvements', [])
    if improvements:
        lines.append('Areas for Improvement:')
        for improvement in improvements:
            clean_improvement = improvement.replace('📝', '[>]')
            lines.append(f'  {clean_improvement}')
        lines.append('')
    lines.append('=' * 30)
    lines.append('Generated by ATS Resume Scorer')
    return '\n'.join(lines)
